### ISSUE TITLE
Math.round is used for fight calculations and it is wrong on 0.5 values

### ISSUE THREAD

**Issue by Serthys** [chimermc/ArtifactsBot#1]
src: https://discord.com/channels/1162610864021590036/1309391849781461012/1317584225771192330
```
so what's the rounding behaviour for 0.5 now? 0.5 -> 1?
Yes
```

On x.5 values Math.ceil should be used instead, C# seems to round to the closest even number by default.
I would recommend creating a global method with the implementation to be reused in multiple places.

**Comment by chimermc** [comment]
Thanks for pointing this out! [It's fixed now.](https://github.com/chimermc/ArtifactsBot/commit/a9e0c3ff45a044fec536a4f2d8b74edb40bca77f)
